# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '5CHackathon2016' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 5CHackathon2016
  pod 'Firebase/Core'
  pod 'Firebase/Database'

  target '5CHackathon2016Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '5CHackathon2016UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
